@ASP_NET_11._TaskFlow_Validation_Global_exception_handler_HostAddress = http://localhost:5151

GET {{ASP_NET_11._TaskFlow_Validation_Global_exception_handler_HostAddress}}/weatherforecast/
Accept: application/json

###
