@ASP_NET_10._TaskFlow_Pagination_Ordering_Filtering_HostAddress = http://localhost:5245

GET {{ASP_NET_10._TaskFlow_Pagination_Ordering_Filtering_HostAddress}}/weatherforecast/
Accept: application/json

###
